CREATE OR REPLACE FUNCTION Task4(id IN NUMBER) 
    return VARCHAR2 
IS
    value INTEGER;
    isExists BO
BEGIN
        SELECT COUNT(*) INTO ID_EXISTS FROM MyTable WHERE ID = ID_TO_CHECK;
        IF ID_EXISTS = 1 THEN RETURN TRUE;
            ELSE RETURN FALSE;
        END IF;

        IF CHECK_ID(ID_TO_INSERT) THEN
            SELECT VAL INTO VALUE FROM MYTABLE WHERE ID = ID_TO_INSERT;
            RETURN CONCAT(CONCAT(CONCAT(CONCAT('INSERT INTO MyTable VALUES(', TO_CHAR(ID_TO_INSERT)),', '), TO_CHAR(VALUE)),');');
        END IF;
        RETURN 'ASHIBKA';
END;

DECLARE
    BEGIN
        DBMS_OUTPUT.PUT_LINE((GENERATE_INSERT(10)));
    END;